#!/usr/bin/env bash
# Script that displays information about specific subdomains

extract() {
    # shellcheck disable=SC2086
    ip=$(dig $2.$1 | awk '$5 ~ /([0-9]{1,3}\.?){3}/ {print $5}')
    echo "The subdomain $2 is a A record and points to $ip"
}

process () {
    if [ $# -eq 2 ]; then
        # shellcheck disable=SC2086    
        extract $1 $2
    else
        subdomains=("www" "lb-01" "web-01" "web-02")
        for i in "${subdomains[@]}"; do
            # shellcheck disable=SC2086
            extract $1 $i
        done
    fi    
}
# shellcheck disable=SC2086
process $1 $2
