#!/usr/bin/env bash
# Script that transfer file from a client to a server

if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
scp -i "$4" "$1" "$3@$2:/home/$3"
