#!/usr/bin/env bash
# Script that installs nginx and configures redirection

sudo apt update -y
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.nginx-debian.html
new="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=hdZUCjAQaGw permanent;/"
sudo sed -i "s/server_name _;/${new}" /etc/nginx/sites-available/default
sudo service nginx restart
