#!/usr/bin/env bash
# Configures haproxy in a new server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4
sudo apt-get install -y haproxy

config="frontend main\n\tbind *:80\n\tdefault_backend webservers\nbackend webservers\n\tbalance roundrobin\n\tserver 4278-web-01 18.212.96.209:80\n\tserver 4278-web-02 54.91.216.10:80"
sudo sed -i "$ a ${config}" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
