#!/usr/bin/env bash
# Configures haproxy in a new server

sudo apt update -y
sudo apt upgrade -y
sudo apt instal haproxy

config="frontend main\n\tbind *:80\n\tdefault_backend webservers\nbackend webservers\n\tbalance roundrobin\n\tserver 4278-web-01 18.212.96.209\n\tserver 4278-web-02 54.91.216.10"
sudo sed -i "$ a ${config}" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
