#!/usr/bin/env bash
# Configures haproxy in a new server

sudo apt update -y
sudo apt upgrade -y
sudo apt instal haproxy

config="frontend main\n\tbind *:80\n\tdefault_backend webservers\nbackend webservers\n\tbalance roundrobin\n\tserver web1 18.212.96.209\n\tserver web2 54.91.216.10"
sudo sed -i "$ a ${config}" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
