#!/usr/bin/env bash
#Script that configures /etc/hosts
cp /etc/hosts /etc/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts.new
cp -f /etc/hosts.new /etc/hosts
echo -e "8.8.8.8\tfacebook.com" >> /etc/hosts
